/**
 * lib/pdf/report-builder.ts
 *
 * Thin layout layer over jsPDF for FinFlow's branded documents (tax summary,
 * CA audit report). jspdf-autotable is not a dependency, so tables are drawn
 * directly — which also keeps column widths and row shading under our control.
 *
 * Client-side only: jsPDF needs a browser to trigger the download.
 */

import jsPDF from "jspdf"

// ─── Brand palette (RGB, matching the app's slate/emerald theme) ───

const INK = [15, 23, 42] as const // slate-900
const MUTED = [100, 116, 139] as const // slate-500
const RULE = [203, 213, 225] as const // slate-300
const BRAND = [16, 185, 129] as const // emerald-500
const BAND = [241, 245, 249] as const // slate-100

const PAGE_WIDTH = 210
const PAGE_HEIGHT = 297
const MARGIN = 14
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2

export interface TableColumn {
  header: string
  /** Fraction of content width, 0–1. Must sum to ~1 across columns. */
  width: number
  align?: "left" | "right"
}

/**
 * Formats a number as Indian rupees without the ₹ glyph.
 *
 * jsPDF's built-in Helvetica is WinAnsi-encoded and renders ₹ as a blank box,
 * so every monetary figure in these reports is prefixed "Rs. " instead.
 */
export function inr(value: number): string {
  const rounded = Math.round(value)
  return `Rs. ${rounded.toLocaleString("en-IN")}`
}

export class ReportBuilder {
  private doc: jsPDF
  private y = MARGIN
  private pageNumber = 1
  private readonly footerNote: string

  constructor(footerNote = "Generated by FinFlow — not a substitute for advice from a practising Chartered Accountant.") {
    this.doc = new jsPDF({ unit: "mm", format: "a4" })
    this.footerNote = footerNote
  }

  // ─── internals ──────────────────────────────────────────

  private setInk(color: readonly [number, number, number] | readonly number[]) {
    this.doc.setTextColor(color[0]!, color[1]!, color[2]!)
  }

  private setFill(color: readonly [number, number, number] | readonly number[]) {
    this.doc.setFillColor(color[0]!, color[1]!, color[2]!)
  }

  /** Adds a page when the next block of `needed` mm would overflow. */
  private ensureSpace(needed: number) {
    if (this.y + needed <= PAGE_HEIGHT - MARGIN - 12) return
    this.drawFooter()
    this.doc.addPage()
    this.pageNumber++
    this.y = MARGIN
  }

  private drawFooter() {
    this.doc.setFontSize(7.5)
    this.doc.setFont("helvetica", "normal")
    this.setInk(MUTED)
    this.doc.text(this.footerNote, MARGIN, PAGE_HEIGHT - 10, { maxWidth: CONTENT_WIDTH - 20 })
    this.doc.text(String(this.pageNumber), PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: "right" })
  }

  // ─── public building blocks ─────────────────────────────

  /** Branded masthead. Call once, first. */
  header(title: string, subtitle: string): this {
    this.setFill(INK)
    this.doc.rect(0, 0, PAGE_WIDTH, 30, "F")

    this.setFill(BRAND)
    this.doc.rect(0, 30, PAGE_WIDTH, 1.2, "F")

    this.doc.setFont("helvetica", "bold")
    this.doc.setFontSize(9)
    this.setInk(BRAND)
    this.doc.text("FINFLOW", MARGIN, 12)

    this.doc.setFontSize(16)
    this.doc.setTextColor(255, 255, 255)
    this.doc.text(title, MARGIN, 21)

    this.doc.setFont("helvetica", "normal")
    this.doc.setFontSize(8.5)
    this.doc.setTextColor(203, 213, 225)
    this.doc.text(subtitle, MARGIN, 26.5)

    this.y = 40
    return this
  }

  /** Section heading with an accent rule. */
  section(title: string): this {
    this.ensureSpace(16)
    this.doc.setFont("helvetica", "bold")
    this.doc.setFontSize(11)
    this.setInk(INK)
    this.doc.text(title, MARGIN, this.y)

    this.setFill(BRAND)
    this.doc.rect(MARGIN, this.y + 1.8, 16, 0.8, "F")
    this.y += 8
    return this
  }

  paragraph(text: string): this {
    this.doc.setFont("helvetica", "normal")
    this.doc.setFontSize(9)
    this.setInk(MUTED)
    const lines = this.doc.splitTextToSize(text, CONTENT_WIDTH) as string[]
    this.ensureSpace(lines.length * 4.4 + 3)
    this.doc.text(lines, MARGIN, this.y)
    this.y += lines.length * 4.4 + 3
    return this
  }

  /** Row of headline figures, evenly divided across the content width. */
  metrics(items: Array<{ label: string; value: string; emphasis?: boolean }>): this {
    if (items.length === 0) return this
    this.ensureSpace(22)

    const cellWidth = CONTENT_WIDTH / items.length
    this.setFill(BAND)
    this.doc.roundedRect(MARGIN, this.y, CONTENT_WIDTH, 18, 1.5, 1.5, "F")

    items.forEach((item, i) => {
      const x = MARGIN + i * cellWidth + 4

      this.doc.setFont("helvetica", "normal")
      this.doc.setFontSize(7)
      this.setInk(MUTED)
      this.doc.text(item.label.toUpperCase(), x, this.y + 6.5)

      this.doc.setFont("helvetica", "bold")
      this.doc.setFontSize(11)
      this.setInk(item.emphasis ? BRAND : INK)
      this.doc.text(item.value, x, this.y + 13.5)
    })

    this.y += 24
    return this
  }

  /** Simple striped table. `rows` cells are pre-formatted strings. */
  table(columns: TableColumn[], rows: string[][]): this {
    const ROW_HEIGHT = 7
    this.ensureSpace(ROW_HEIGHT * 2)

    const widths = columns.map((c) => c.width * CONTENT_WIDTH)
    const xFor = (index: number) => MARGIN + widths.slice(0, index).reduce((a, b) => a + b, 0)

    const drawHeader = () => {
      this.setFill(INK)
      this.doc.rect(MARGIN, this.y, CONTENT_WIDTH, ROW_HEIGHT, "F")
      this.doc.setFont("helvetica", "bold")
      this.doc.setFontSize(8)
      this.doc.setTextColor(255, 255, 255)

      columns.forEach((col, i) => {
        const right = col.align === "right"
        this.doc.text(
          col.header,
          right ? xFor(i) + widths[i]! - 2.5 : xFor(i) + 2.5,
          this.y + 4.8,
          { align: right ? "right" : "left" }
        )
      })
      this.y += ROW_HEIGHT
    }

    drawHeader()

    rows.forEach((row, rowIndex) => {
      if (this.y + ROW_HEIGHT > PAGE_HEIGHT - MARGIN - 12) {
        this.drawFooter()
        this.doc.addPage()
        this.pageNumber++
        this.y = MARGIN
        drawHeader()
      }

      if (rowIndex % 2 === 1) {
        this.setFill(BAND)
        this.doc.rect(MARGIN, this.y, CONTENT_WIDTH, ROW_HEIGHT, "F")
      }

      this.doc.setFont("helvetica", "normal")
      this.doc.setFontSize(8.5)
      this.setInk(INK)

      columns.forEach((col, i) => {
        const right = col.align === "right"
        const cell = row[i] ?? ""
        this.doc.text(
          cell,
          right ? xFor(i) + widths[i]! - 2.5 : xFor(i) + 2.5,
          this.y + 4.8,
          { align: right ? "right" : "left", maxWidth: widths[i]! - 5 }
        )
      })

      this.y += ROW_HEIGHT
    })

    this.setInk(RULE)
    this.doc.setDrawColor(RULE[0], RULE[1], RULE[2])
    this.doc.line(MARGIN, this.y, PAGE_WIDTH - MARGIN, this.y)
    this.y += 8
    return this
  }

  /** Highlighted callout used for the regime recommendation. */
  callout(title: string, body: string): this {
    this.doc.setFont("helvetica", "normal")
    this.doc.setFontSize(9)
    const lines = this.doc.splitTextToSize(body, CONTENT_WIDTH - 10) as string[]
    const height = lines.length * 4.4 + 14
    this.ensureSpace(height)

    this.setFill([236, 253, 245]) // emerald-50
    this.doc.roundedRect(MARGIN, this.y, CONTENT_WIDTH, height, 1.5, 1.5, "F")
    this.setFill(BRAND)
    this.doc.rect(MARGIN, this.y, 1.2, height, "F")

    this.doc.setFont("helvetica", "bold")
    this.doc.setFontSize(9.5)
    this.setInk(INK)
    this.doc.text(title, MARGIN + 5, this.y + 6.5)

    this.doc.setFont("helvetica", "normal")
    this.doc.setFontSize(9)
    this.setInk(MUTED)
    this.doc.text(lines, MARGIN + 5, this.y + 12)

    this.y += height + 6
    return this
  }

  bullets(items: string[]): this {
    this.doc.setFont("helvetica", "normal")
    this.doc.setFontSize(9)

    items.forEach((item) => {
      const lines = this.doc.splitTextToSize(item, CONTENT_WIDTH - 6) as string[]
      this.ensureSpace(lines.length * 4.4 + 2)
      this.setInk(BRAND)
      this.doc.text("•", MARGIN, this.y)
      this.setInk(MUTED)
      this.doc.text(lines, MARGIN + 4, this.y)
      this.y += lines.length * 4.4 + 2
    })

    this.y += 4
    return this
  }

  spacer(mm = 4): this {
    this.y += mm
    return this
  }

  /** Finalises the footer on the last page and triggers the download. */
  save(fileName: string): void {
    this.drawFooter()
    this.doc.save(fileName)
  }

  /** Escape hatch for callers that need the raw document (e.g. blob upload). */
  output(): Blob {
    this.drawFooter()
    return this.doc.output("blob")
  }
}
