/**
 * server/services/tax/form16.parser.ts
 *
 * Extracts structured salary, exemption, deduction and TDS figures from an
 * employer-issued Form 16 (Part A + Part B) PDF.
 *
 * Approach: Form 16 is generated by TRACES from a fixed template, so the
 * statutory labels ("Gross Salary", "Total amount of salary received from
 * current employer", "Aggregate of deductible amount under Chapter VI-A") are
 * stable even though layout, fonts and column order vary by payroll vendor.
 * We therefore anchor on those labels and take the nearest rupee figure, rather
 * than relying on positional table extraction which breaks across vendors.
 *
 * Every field the parser could not locate is reported in `missingFields` so the
 * filing wizard can ask the user instead of silently filing a zero.
 */

import { extractPdfText } from "@/lib/pdf/extractText"
import { decryptPDF } from "@/server/services/parser/pdf.decrypt"
import type { Form16Data } from "./types"
import { safeLogError } from "@/server/lib/safe-log"

// ─── Number handling ────────────────────────────────────────

/**
 * Parses an Indian-formatted rupee figure.
 *
 * Handles "1,23,456.78", "123456", "(1,234)" (negative in accounting form) and
 * "Rs. 1,23,456/-". Returns null when the token is not a number, so callers can
 * distinguish "absent" from "zero".
 */
export function parseRupees(raw: string | undefined | null): number | null {
  if (!raw) return null
  const cleaned = raw
    .replace(/rs\.?|inr|₹/gi, "")
    .replace(/\/-\s*$/, "")
    .replace(/[,\s]/g, "")
    .trim()

  const negative = /^\(.*\)$/.test(cleaned)
  const digits = cleaned.replace(/[()]/g, "")
  if (!/^-?\d+(\.\d{1,2})?$/.test(digits)) return null

  const value = Number(digits)
  if (!Number.isFinite(value)) return null
  return negative ? -value : value
}

/** All rupee-looking figures in a chunk of text, in order of appearance. */
function figuresIn(text: string): number[] {
  const matches = text.match(/\(?-?(?:\d{1,3}(?:,\d{2,3})+|\d+)(?:\.\d{1,2})?\)?/g) ?? []
  return matches
    .map((m) => parseRupees(m))
    .filter((n): n is number => n !== null)
}

/**
 * Finds the figure that belongs to a label.
 *
 * Form 16 lines look like:
 *   "1(a) Gross Salary as per provisions contained in sec 17(1)   12,50,000.00"
 * The label itself often contains section numbers ("17(1)", "80CCD(1B)") that
 * look like figures, so we only scan the text *after* the label match and stop
 * at the first plausible rupee amount — optionally continuing onto the next
 * line, since narrow templates wrap the amount.
 */
function findAmount(text: string, patterns: RegExp[], opts: { lookaheadChars?: number } = {}): number | null {
  const lookahead = opts.lookaheadChars ?? 160

  for (const pattern of patterns) {
    const match = pattern.exec(text)
    if (!match) continue

    const tail = text.slice(match.index + match[0].length, match.index + match[0].length + lookahead)
    // Drop parenthesised section references like "(1B)" or "17(2)" that precede
    // the real amount on the same line.
    const withoutSectionRefs = tail.replace(/\b\d{1,3}\s*\([0-9A-Za-z]{1,3}\)/g, " ")
    const candidates = figuresIn(withoutSectionRefs)
    const amount = candidates.find((n) => Math.abs(n) >= 1)
    if (amount !== undefined) return amount
  }

  return null
}

function findText(text: string, pattern: RegExp): string | undefined {
  const match = pattern.exec(text)
  return match?.[1]?.trim()
}

// ─── Chapter VI-A ───────────────────────────────────────────

/** Sections we actively look for, in the order they appear on the form. */
const CHAPTER_VIA_SECTIONS = [
  "80C",
  "80CCC",
  "80CCD(1)",
  "80CCD(1B)",
  "80CCD(2)",
  "80D",
  "80DD",
  "80DDB",
  "80E",
  "80EE",
  "80EEA",
  "80EEB",
  "80G",
  "80GG",
  "80GGA",
  "80TTA",
  "80TTB",
  "80U",
] as const

/**
 * Form 16 reports both the "gross amount" and the "deductible amount" for each
 * Chapter VI-A section — the deductible amount is the capped one and is what
 * actually reduces taxable income. When both are on the line we take the last
 * figure, which is the deductible column in the TRACES layout.
 */
function extractChapterVIA(text: string): Record<string, number> {
  const result: Record<string, number> = {}

  for (const section of CHAPTER_VIA_SECTIONS) {
    // "80CCD(1B)" must not be matched by the "80CCD(1)" pattern, so the
    // sub-clause is matched exactly rather than as a prefix.
    const escaped = section.replace(/[()]/g, (c) => `\\${c}`)
    const pattern = new RegExp(
      `(?:section|u/s|under)?\\s*${escaped}(?![0-9A-Za-z(])[^\\n]*`,
      "i"
    )
    const match = pattern.exec(text)
    if (!match) continue

    const line = match[0].replace(new RegExp(escaped, "i"), " ")
    const figures = figuresIn(line).filter((n) => n >= 1)
    if (figures.length === 0) continue

    // Last figure on the line = deductible (capped) amount.
    result[section] = figures[figures.length - 1]!
  }

  return result
}

// ─── Quarterly TDS (Part A) ─────────────────────────────────

/**
 * Part A tabulates TDS by quarter:
 *   "Q1  QRTNAA  1,25,000.00  1,25,000.00  1,25,000.00"
 * The last column is the amount deposited, which is what reconciles to 26AS.
 */
function extractQuarterlyTds(text: string): Array<{ quarter: string; receiptNumber?: string; amountDeposited: number }> {
  const rows: Array<{ quarter: string; receiptNumber?: string; amountDeposited: number }> = []
  const pattern = /\bQ([1-4])\b([^\n]*)/gi

  let match: RegExpExecArray | null
  while ((match = pattern.exec(text)) !== null) {
    const line = match[2] ?? ""
    const receipt = /\b([A-Z]{6,10})\b/.exec(line)?.[1]
    const figures = figuresIn(line).filter((n) => n >= 1)
    if (figures.length === 0) continue

    rows.push({
      quarter: `Q${match[1]}`,
      receiptNumber: receipt,
      amountDeposited: figures[figures.length - 1]!,
    })
  }

  // A quarter can appear in both the summary and the detail table; keep the
  // first (summary) occurrence per quarter.
  const seen = new Set<string>()
  return rows.filter((row) => {
    if (seen.has(row.quarter)) return false
    seen.add(row.quarter)
    return true
  })
}

// ─── Main parser ────────────────────────────────────────────

export interface Form16ParseOptions {
  /** Password for an encrypted Form 16 (usually the employee's PAN or DOB). */
  password?: string
}

export async function parseForm16(
  buffer: Buffer,
  options: Form16ParseOptions = {}
): Promise<Form16Data> {
  let text: string

  try {
    const decrypted = await decryptPDF(buffer, options.password)
    const extracted = await extractPdfText(decrypted.buffer)
    text = extracted.text
  } catch (error) {
    safeLogError("[FORM16] Text extraction failed", error)
    throw new Error("Could not read this Form 16 PDF. If it is password-protected, supply the password.")
  }

  return parseForm16Text(text)
}

/** Exported separately so the text path is unit-testable without a PDF. */
export function parseForm16Text(rawText: string): Form16Data {
  // Collapse runs of spaces but keep line structure: label→amount adjacency
  // matters, line breaks do not.
  const text = rawText.replace(/[ \t]{2,}/g, " ")
  const missingFields: string[] = []

  const require = <T>(value: T | null, field: string, fallback: T): T => {
    if (value === null || value === undefined) {
      missingFields.push(field)
      return fallback
    }
    return value
  }

  // ─── Salary components (Part B, item 1) ───────────────────

  const grossSalary = require(
    findAmount(text, [
      /gross\s+salary[^\n]*?\btotal\b/i,
      /total\s+amount\s+of\s+salary\s+received\s+from\s+current\s+employer/i,
      /\bgross\s+salary\b/i,
    ]),
    "grossSalary",
    0
  )

  const perquisites =
    findAmount(text, [
      /value\s+of\s+perquisites\s+u\/?s?\s*17\s*\(?2\)?/i,
      /perquisites\s+under\s+section\s+17\s*\(?2\)?/i,
    ]) ?? 0

  const profitsInLieu =
    findAmount(text, [
      /profits\s+in\s+lieu\s+of\s+salary[^\n]*17\s*\(?3\)?/i,
      /profits\s+in\s+lieu\s+of\s+salary/i,
    ]) ?? 0

  // ─── Section 10 exemptions ────────────────────────────────

  const hra =
    findAmount(text, [
      /house\s+rent\s+allowance\s+under\s+section\s+10\s*\(?13A\)?/i,
      /\bHRA\b[^\n]*exempt/i,
      /section\s+10\s*\(?13A\)?/i,
    ]) ?? 0

  const lta =
    findAmount(text, [
      /(?:travel\s+concession|leave\s+travel)[^\n]*10\s*\(?5\)?/i,
      /section\s+10\s*\(?5\)?/i,
    ]) ?? 0

  const gratuity =
    findAmount(text, [/death[- ]cum[- ]retirement\s+gratuity[^\n]*10\s*\(?10\)?/i]) ?? 0

  const totalExemption =
    findAmount(text, [
      /total\s+amount\s+of\s+exemption\s+claimed\s+under\s+section\s+10/i,
      /total\s+exemption[^\n]*section\s+10/i,
    ]) ?? hra + lta + gratuity

  const otherExemption = Math.max(0, totalExemption - (hra + lta + gratuity))

  // ─── Section 16 deductions ────────────────────────────────

  const standardDeduction = require(
    findAmount(text, [
      /standard\s+deduction\s+under\s+section\s+16\s*\(?ia\)?/i,
      /standard\s+deduction/i,
    ]),
    "standardDeduction",
    0
  )

  const professionalTax =
    findAmount(text, [
      /tax\s+on\s+employment\s+under\s+section\s+16\s*\(?iii\)?/i,
      /professional\s+tax/i,
    ]) ?? 0

  // ─── Other heads reported to the employer ─────────────────

  // Almost always negative (a self-occupied house loan loss set off against
  // salary), so the sign is preserved rather than forced positive.
  const housePropertyIncome =
    findAmount(text, [
      /income\s*\(?or\s+admissible\s+loss\)?\s+from\s+house\s+property/i,
      /loss\s+from\s+house\s+property/i,
      /income\s+from\s+house\s+property/i,
    ]) ?? 0

  const otherSourcesIncome =
    findAmount(text, [
      /income\s+under\s+the\s+head\s+other\s+sources\s+offered\s+for\s+TDS/i,
      /income\s+from\s+other\s+sources/i,
    ]) ?? 0

  // ─── Chapter VI-A ─────────────────────────────────────────

  const chapterVIA = extractChapterVIA(text)
  if (Object.keys(chapterVIA).length === 0) {
    missingFields.push("chapterVIA")
  }

  // ─── TDS ──────────────────────────────────────────────────

  const quarterlyTds = extractQuarterlyTds(text)
  const quarterlyTotal = quarterlyTds.reduce((sum, q) => sum + q.amountDeposited, 0)

  const statedTds = findAmount(text, [
    /total\s+tax\s+deducted\s+at\s+source[^\n]*/i,
    /net\s+tax\s+payable/i,
    /total\s+amount\s+of\s+tax\s+deposited[^\n]*/i,
  ])

  const totalTdsDeposited = statedTds ?? quarterlyTotal
  if (totalTdsDeposited === 0) missingFields.push("totalTdsDeposited")

  // ─── Identity ─────────────────────────────────────────────

  const pans = text.match(/\b[A-Z]{5}\d{4}[A-Z]\b/g) ?? []
  const tan = findText(text, /\b([A-Z]{4}\d{5}[A-Z])\b/)

  const employeePan =
    findText(text, /PAN\s+of\s+(?:the\s+)?(?:Employee|Deductee)[^A-Z]*([A-Z]{5}\d{4}[A-Z])/i) ??
    pans[pans.length - 1]

  const employerPan =
    findText(text, /PAN\s+of\s+(?:the\s+)?(?:Deductor|Employer)[^A-Z]*([A-Z]{5}\d{4}[A-Z])/i) ??
    pans[0]

  const employerName = findText(
    text,
    /Name\s+and\s+address\s+of\s+the\s+(?:Employer|Deductor)\s*:?\s*([^\n]{3,80})/i
  )

  const employeeName = findText(
    text,
    /Name\s+and\s+address\s+of\s+the\s+(?:Employee|Deductee)\s*:?\s*([^\n]{3,80})/i
  )

  const assessmentYear = findText(text, /Assessment\s+Year\s*:?\s*(\d{4}\s*-\s*\d{2,4})/i)?.replace(/\s/g, "")

  // ─── Confidence ───────────────────────────────────────────
  // Share of the anchors we consider load-bearing that were actually found.

  const anchors = [
    grossSalary > 0,
    standardDeduction > 0,
    totalTdsDeposited > 0,
    Object.keys(chapterVIA).length > 0,
    Boolean(employeePan),
    Boolean(assessmentYear),
  ]
  const confidence = anchors.filter(Boolean).length / anchors.length

  return {
    grossSalary,
    perquisites,
    profitsInLieu,
    exemptions: {
      hra,
      lta,
      gratuity,
      other: otherExemption,
      total: totalExemption,
    },
    standardDeduction,
    professionalTax,
    housePropertyIncome,
    otherSourcesIncome,
    chapterVIA,
    totalTdsDeposited,
    employer: { name: employerName, tan, pan: employerPan },
    employee: { name: employeeName, pan: employeePan },
    assessmentYear,
    quarterlyTds,
    missingFields,
    confidence,
  }
}
